import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { Section } from "../components/sections";
import styles from "../styles/Home.module.css";
import { gql, request } from "graphql-request";
import { CustomerReview } from "../components/sections/CustReviewsSection";

type HomeProps = {
  customerReviewCards: CustomerReview[];
};

const Home = ({ customerReviewCards }: HomeProps) => {
  return (
    <div className={styles._container}>
      <Head>
        <title>Fat Slob Plumbing</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Intro Section */}
      <Section.Intro />
      {/* How We Work */}
      <Section.HowWeWork />
      {/* Services */}
      <Section.Services />
      {/* Customer Reviews */}
      <Section.CustReviews data={customerReviewCards}></Section.CustReviews>
      {/* Franchises */}
      <Section.Franchises />
      {/* Valued Partners */}
      <Section.Partners />
      {/* About Us */}
      <Section.AboutUs />
      {/* Footer */}

      <main className={styles.main}>
        <div className={styles.grid}></div>
      </main>

      <Section.Footer></Section.Footer>
      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;

export async function getStaticProps() {
  const query = gql`
    {
      customerReviews {
        customerName
        id
        review
        photo
      }
    }
  `;

  const data = await request(
    "https://api-eu-central-1-shared-euc1-02.hygraph.com/v2/cl9cidxte4hnw01ueb5tfbvuh/master",
    query
  );
  return {
    props: {
      customerReviews: data.customerReviews,
    }, // will be passed to the page component as props
  };
}
